# path to samplesheet
samplesheet: samples.csv

fastq_dir: fastqs

reference:

chrom_sizes: 

threads: 4

adaptor_5p: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
adaptor_3p: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
min_len: 20
