# path to samplesheet
samplesheet: samples.csv

fastq_dir: fastqs

reference:
reference_spikein:

exclusion_list: assets/exclusion_list_encode4_GRCh38_ENCFF356LFX.bed

chrom_sizes: assets/reference/Homo_sapiens/NCBI/GRCh38/chrom.sizes

threads: 4

adaptor_5p: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
adaptor_3p: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
min_len: 20
