# path to samplesheet
samplesheet: samples.csv

fastq_dir: fastqs

reference: /Users/rmmeyers/genomes/Homo_sapiens/NCBI/GRCh38/Sequence/Bowtie2Index/genome

chrom_sizes: /Users/rmmeyers/genomes/Homo_sapiens/NCBI/GRCh38/Sequence/chrom.sizes

threads: 4

adaptor_5p: AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
adaptor_3p: AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
min_len: 20
