# path to samplesheet
samplesheet: samples.csv

fastq_dir: fastqs

reference: $HOME/genomes/Homo_sapiens/NCBI/GRCh38/Sequence/Bowtie2Index/genome

chrom_sizes: $HOME/genomes/Homo_sapiens/NCBI/GRCh38/Sequence/chrom.sizes

threads: 4

adaptor_5p: GATCGGAAGAGCACACGTCTGAACTCCAGTCAC
adaptor_3p: GATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
min_len: 20