name: cutnrun-snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake
  - bedtools
  - pandas
  - fastqc
  - cutadapt
  - picard
  - bowtie2
  - ucsc-bedgraphtobigwig
  - samtools=1.10
  - biopython